### ISSUE TITLE
Define an epic issue for the first release

### ISSUE THREAD

**Issue by skabashnyuk** [elfmz/far2l#270]
I think many users who like ***FAR2L*** wants to have easy ability to install some released version. 
To make it happy it would be nice to see an issue with defined

 - [ ] bugs to be fixed
 - [ ] features to implement
 - [ ] packaging have to be done
 - [ ] any legal or other paper work to be done
 - [ ] post release actions. Like activity on some sites, blogs etc.

wdyt?

**Comment by elfmz** [comment]
looks like a dup for https://github.com/elfmz/far2l/issues/169

**Comment by skabashnyuk** [comment]
yes. sorry.

**Comment by yujiaao** [comment]
Sounds great! I am happy to have a Far2l release!


________________________________
发件人: Sergii Kabashniuk <notifications@github.com>
发送时间: 2017年3月29日 11:16
收件人: elfmz/far2l
抄送: Subscribed
主题: [elfmz/far2l] Define an epic issue for the first release (#270)


I think many users who like FAR2L wants to have easy ability to install some released version.
To make it happy it would be nice to see an issue with defined

  *    bugs to be fixed
  *    features to implement
  *    packaging have to be done
  *    any legal or other paper work to be done
  *    post release actions. Like activity on some sites, blogs etc.

wdyt?

―
